### ISSUE TITLE
Spamming F5 adds your name multiple times

### ISSUE THREAD

**Issue by SVNKoch** [eum2o/planning-poker#20]
when the tab is refreshed in really quick succession, you join multiple times

**Comment by SVNKoch** [comment]
Once the consensus "screen" is reached and someone refreshse they rejoin without their vote thus the consensurs "screen" is disabled again. Furthermore as the person leaves the average can change
(Maybe related to #1)

**Comment by eum2o** [comment]
We can also think about adding a warning "Do you really want to leave this page?" as some answers in https://stackoverflow.com/q/5711815/5207900 document.

It really makes no sense to refresh PPP, so maybe we don't need to put too much effort into making it work smoothly but instead make it harder to actually refresh.

**Comment by ingomohr** [comment]
Though I understand the motivation, I wouldn't love the app to spawn modals on me when I refresh the browser. I always considered those "u want 2 leave?" modals kind of annoying. 😉

**Comment by eum2o** [comment]
I cannot reproduce this locally. Maybe this is an issue only if the server is running on a remote machine.

**Comment by eum2o** [comment]
Closed due to inactivity. I wasn't able to reproduce it locally. We did not had any problem with this bug while using PPP. And maybe it's gone after #44
