### ISSUE TITLE
Add tooltips for vote options

### ISSUE THREAD

**Issue by SVNKoch** [eum2o/planning-poker#22]
add tooltips for the ✂🤷‍♀️🍵 buttons

**Comment by eum2o** [comment]
Meanings (not supposed to be used as final tooltip texts):
- 🍵: I need a break.
- 🤷‍♀️: I have no idea what to estimate.
- ✂: User story too big. Needs to be cut.

Regarding the implementation I suggest to extend `valueToCardLabel` in https://github.com/eum2o/planning-poker/blob/master/src/cards.js by an optional description.

**Comment by Sdaewa** [comment]
Hi! can I get this assigned?

**Comment by eum2o** [comment]
Hello @Sdaewa! Just wanted to let you know that there's already a draft for this issue available at https://github.com/eum2o/planning-poker/pull/24. Feel free to join the discussion in the PR.

Alternatively, you can assign yourself to this issue and create an alternative pull request to implement it. Thank you for your interest! :)

**Comment by eum2o** [comment]
Okay the request now is implemented. But you are welcome to implement any other issue in this repo @Sdaewa.
