### ISSUE TITLE
Add Link to Github Repo

### ISSUE THREAD

**Issue by eum2o** [eum2o/planning-poker#25]
Add a link to this GitHub repo in the UI. For example in the footer or whatever looks good.

Motivation: Users using this app can quickly jump to this repo to create issues or to contribute.

**Comment by sohaibaumer** [comment]
can i get assigned?

**Comment by eum2o** [comment]
@sohaibaumer yes sure, thank you :)

By the way it's not required to update the screenshots in the readme, imo.
