### ISSUE TITLE
Consent Feels Wrong - Maybe we Should Make Things more Clear - or fix it

### ISSUE THREAD

**Issue by ingomohr** [eum2o/planning-poker#27]
![image](https://github.com/eum2o/planning-poker/assets/2838592/06bd1ca7-ec91-4a0d-a526-5ee771697964)

**Comment by eum2o** [comment]
It's not a bug. From the user guide:

> Once everyone has voted, the most commonly selected card will be displayed

**Comment by eum2o** [comment]
But I think we should indeed update the algorithm. In the scenario described in the issue description, the consensus should be 8.

**Comment by eum2o** [comment]
Updated the calculcation of the concensus to be a little smarter: The algorithm calculates the average of all user estimations and selects the nearest higher or equal predefined value, determining the group's consensus.

See this test for a demonstration: https://github.com/eum2o/planning-poker/blob/master/src/components/EstimationSummary.test.js

**Comment by eum2o** [comment]
@ingomohr if you don't like the algo and if you have something else in mind, feel free to reopen this issue. I didn't want to bother you with a discussion or review so I just implemented it the way I thought it makes sense.

**Comment by eum2o** [comment]
Updated it again. It's not "nearest higher or equal predefined value (of the average)" but "nearest predefined value (of the average)" now
