### ISSUE TITLE
Consent Feels Wrong (Still)

### ISSUE THREAD

**Issue by eum2o** [eum2o/planning-poker#40]
In the context of #27 the algorithm was updates but it's steel weird:

![image](https://github.com/eum2o/planning-poker/assets/1593923/b0d11054-ce3d-4685-aea0-24572b918f0d)

![image](https://github.com/eum2o/planning-poker/assets/1593923/c8f72c05-8c0c-40e7-9cdc-dc734a4810a1)

💡 
* Code: [EstimationSummary.jsx#L49-L67](https://github.com/eum2o/planning-poker/blob/2cecec108794f050b73e37ed6bed05180e731ffb/src/components/EstimationSummary.jsx#L49-L67)
* Test: [EstimationSummary.test.js](https://github.com/eum2o/planning-poker/blob/master/src/components/EstimationSummary.test.js)

**Comment by eum2o** [comment]
Some ideas brainstormed with DevCore:

- Calculating the median seems appropriate in case someone who has no idea is completely out of range.
  - Eg. 1, 1, 1, 21 -> the 21 guy probably doesn't know what he's doing.
- Change "Consensus" to something like "Suggestion" because that's what it's actually is
- If the algorithm is based on the average
  - Select/suggest the card that is the closest to the average (no matter if it's lower or greater than the average)
  - Idea: Below the suggestion (current consensus), also display the average for reference (with much smaller font)

**Comment by ingomohr** [comment]
## Thoughts on impl: Separation of Concerns should be improved
The logic for the computing the consent is contained in the UI component (React component) `EstimationSummary`. It should be provided in its own file.

**Comment by ingomohr** [comment]
### Change: Median is now Used
* The consensus now is computed as the median (i.e. the middle card in the sorted list of cards)
  * If number of cards is even, the median shifts one card to the right (i.e. it's the median of 4 cards is card number 3)
<img width="605" alt="image" src="https://github.com/eum2o/planning-poker/assets/2838592/fece478d-e8cc-455b-8c56-de89b5c36159">

* Special cards "Need a break" and "Don't know" are ignored
* The 'label' of the median-card is displayed now - i.e. if "cut into smaller parts" is the median, the scissors will be displayed
<img width="1124" alt="image" src="https://github.com/eum2o/planning-poker/assets/2838592/e9b6d7e2-9ac3-42e1-9faa-624a46b6f2ff">

**Comment by ingomohr** [comment]
@eum2o I requested a code review for the linked PR. For more information pls see the PR.
